unit TestUProdutos;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UProdutos;

type
  // Test methods for class TProduto

  TestTProduto = class(TTestCase)
  strict private
    FProduto: TProduto;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestComprarProduto;
    procedure TestVerificarDesconto;
  end;

implementation

procedure TestTProduto.SetUp;
begin
  FProduto := TProduto.Create;
end;

procedure TestTProduto.TearDown;
begin
  FProduto.Free;
  FProduto := nil;
end;

procedure TestTProduto.TestComprarProduto;
var
  ReturnValue: Double;
  pQuantidade: Integer;
begin
  pQuantidade:= 3;

  ReturnValue := FProduto.ComprarProduto(pQuantidade);
  checkEquals(0, ReturnValue, 'Erro no método Comprar');
end;

procedure TestTProduto.TestVerificarDesconto;
var
  ReturnValue: Double;
  pQuantidade: Integer;
  xValorEsperado: Variant;
begin
  pQuantidade := 10;

  ReturnValue := FProduto.VerificarDesconto(pQuantidade);
  CheckEquals(0, ReturnValue, 'Erro no método Verificar Desconto');

  pQuantidade := 50;

  xValorEsperado := 0.9;
  ReturnValue := FProduto.VerificarDesconto(pQuantidade);
  CheckEquals(xValorEsperado, ReturnValue, 'Erro no método Verificar Desconto');

  pQuantidade := 150;

  ReturnValue := FProduto.VerificarDesconto(pQuantidade);
  CheckEquals(0.75, ReturnValue, 'Erro no método Verificar Desconto');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTProduto.Suite);
end.

